theme = "solarized_light"

[editor]
line-number = "relative"
mouse = true
bufferline = "never"
completion-trigger-len = 1
color-modes = true
auto-info = true
popup-border = "all"
end-of-line-diagnostics = "hint"
completion-timeout = 5
true-color = true
insert-final-newline = false
rounded-corners = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "file-encoding", "register", "position-percentage"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.aliases]
blame = ["sh git blame -L %{cursor_line},+1 %{buffer_name}"]

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping

[editor.smart-tab]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-7 = ["toggle_comments"]
# C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
X = ["extend_line_up", "extend_to_line_bounds"]
C-h = ["jump_view_left"]
C-j = ["jump_view_down"]
C-k = ["jump_view_up"]
C-l = ["jump_view_right"]
C-n = ["file_tree"]
D = "@xd"
Y = "@xy"
y = ["yank", "collapse_selection"] 

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"
x = ":write-buffer-close"

[keys.normal.space.t]
h = ":toggle lsp.display-inlay-hints"



